JSON_VALIDATION_ERROR = 'Request body must be a JSON object.'
INVALID_UUID_ERROR = 'Invalid UUID format for {field}.'
INCIDENT_NOT_FOUND = 'Incident not found.'
UNAUTHORIZED_INCIDENT_ERROR = 'You are not allowed to access this incident.'
CLOSED_INCIDENT_ERROR = 'Incident is already closed.'
